name: plantilla_vgv
description: Esta es una plantilla de proyecto de Flutter con las dependencias que usamos en Very Good Ventures.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

# Dependencias de la plantilla
dependencies:
  auto_route: ^9.3.0+1 #Manejo de rutas
  bloc: ^8.1.4 #Manejo de estados
  dio: ^5.8.0+1 #Manejador de peticiones HTTP
  equatable: ^2.0.7 #Comparador de objetos (trabaja junto a bloc)
  flutter:
    sdk: flutter
 
  flutter_bloc: ^8.1.6 #Manejo de estados dentro de flutter
  flutter_localizations: #Manejo de localizaciones
    sdk: flutter
  flutter_svg: ^2.0.17 #Manejador de SVG
  get_it: ^8.0.3 #Manejador de inyección de dependencias
  intl: ^0.19.0 #Manejador de internacionalización
  logger: ^2.5.0 #Manejador de logs
  talker: ^4.6.12 #Manejador de logs de manera visual
  talker_flutter: ^4.6.12 #Manejador de logs de manera visual
dev_dependencies:
  auto_route_generator: ^9.3.1 #Generador de rutas
  bloc_test: ^9.1.7 #Manejador de pruebas unitarias
  build_runner: ^2.4.15 #Manejador de generadores de código
  flutter_test: 
    sdk: flutter
  mocktail: ^1.0.4 #Manejador de mocks
  very_good_analysis: ^7.0.0 #Manejador de análisis de código

flutter:
  uses-material-design: true
  generate: true
  # manejo de assets y fonts
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/fonts/

